-- One-time migration for databases using the old CATEGORY_PATH / CATEGORY schema.
-- Take a database backup first. Run this script once, before deploying the new app.

RENAME TABLE MODUWMNL_CATEGORY TO MODUWMNL_CATEGORY_LEGACY;

CREATE TABLE MODUWMNL_CATEGORY (
    CATEGORY_ID        BIGINT NOT NULL AUTO_INCREMENT,
    PARENT_CATEGORY_ID BIGINT NULL,
    CATEGORY_NM        VARCHAR(100) NOT NULL,
    SORT_ORD           INT NOT NULL DEFAULT 0,
    USE_YN             CHAR(1) NOT NULL DEFAULT 'Y',
    FSR_DTM            DATETIME NOT NULL,
    FSR_STF_NO         VARCHAR(30) NULL,
    LSH_DTM            DATETIME NOT NULL,
    LSH_STF_NO         VARCHAR(30) NULL,
    PRIMARY KEY (CATEGORY_ID),
    CONSTRAINT FK_EZHOWTOUSE_MWC_PARENT_V1
        FOREIGN KEY (PARENT_CATEGORY_ID) REFERENCES MODUWMNL_CATEGORY (CATEGORY_ID),
    KEY IX_MODUWMNL_CATEGORY_TREE (PARENT_CATEGORY_ID, USE_YN, SORT_ORD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Build one mapping row for every folder and every implied parent folder.
CREATE TABLE TMP_MODUWMNL_CATEGORY_PATH (
    FULL_PATH   VARCHAR(300) NOT NULL,
    PARENT_PATH VARCHAR(300) NULL,
    CATEGORY_NM VARCHAR(100) NOT NULL,
    DEPTH       INT NOT NULL,
    CATEGORY_ID BIGINT NULL,
    PRIMARY KEY (FULL_PATH)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO TMP_MODUWMNL_CATEGORY_PATH (FULL_PATH, PARENT_PATH, CATEGORY_NM, DEPTH)
WITH RECURSIVE path_nodes AS (
    SELECT CATEGORY_PATH AS FULL_PATH,
           SUBSTRING_INDEX(CATEGORY_PATH, '/', 1) AS NODE_PATH,
           1 AS DEPTH
    FROM MODUWMNL_CATEGORY_LEGACY
    WHERE USE_YN = 'Y'
    UNION ALL
    SELECT FULL_PATH,
           CONCAT(NODE_PATH, '/', SUBSTRING_INDEX(SUBSTRING_INDEX(FULL_PATH, '/', DEPTH + 1), '/', -1)),
           DEPTH + 1
    FROM path_nodes
    WHERE DEPTH < 1 + LENGTH(FULL_PATH) - LENGTH(REPLACE(FULL_PATH, '/', ''))
)
SELECT NODE_PATH,
       CASE WHEN DEPTH = 1 THEN NULL ELSE SUBSTRING_INDEX(NODE_PATH, '/', DEPTH - 1) END,
       SUBSTRING_INDEX(NODE_PATH, '/', -1),
       DEPTH
FROM path_nodes
GROUP BY NODE_PATH, DEPTH;

DELIMITER $$
CREATE PROCEDURE MIGRATE_MODUWMNL_CATEGORY_TREE()
BEGIN
    DECLARE current_depth INT DEFAULT 1;
    DECLARE max_depth INT;
    SELECT MAX(DEPTH) INTO max_depth FROM TMP_MODUWMNL_CATEGORY_PATH;

    WHILE current_depth <= max_depth DO
        INSERT INTO MODUWMNL_CATEGORY
            (PARENT_CATEGORY_ID, CATEGORY_NM, SORT_ORD, USE_YN, FSR_DTM, FSR_STF_NO, LSH_DTM, LSH_STF_NO)
        SELECT parent.CATEGORY_ID, map.CATEGORY_NM, map.DEPTH, 'Y', NOW(), 'migration', NOW(), 'migration'
        FROM TMP_MODUWMNL_CATEGORY_PATH map
        LEFT JOIN TMP_MODUWMNL_CATEGORY_PATH parent ON parent.FULL_PATH = map.PARENT_PATH
        WHERE map.DEPTH = current_depth;

        UPDATE TMP_MODUWMNL_CATEGORY_PATH map
        JOIN MODUWMNL_CATEGORY category
          ON category.CATEGORY_NM = map.CATEGORY_NM
         AND category.PARENT_CATEGORY_ID <=> (
             SELECT parent.CATEGORY_ID FROM TMP_MODUWMNL_CATEGORY_PATH parent WHERE parent.FULL_PATH = map.PARENT_PATH
         )
        SET map.CATEGORY_ID = category.CATEGORY_ID
        WHERE map.DEPTH = current_depth;

        SET current_depth = current_depth + 1;
    END WHILE;
END$$
DELIMITER ;

CALL MIGRATE_MODUWMNL_CATEGORY_TREE();
DROP PROCEDURE MIGRATE_MODUWMNL_CATEGORY_TREE;

ALTER TABLE MODUWMNL ADD COLUMN CATEGORY_ID BIGINT NULL;
UPDATE MODUWMNL manual
JOIN TMP_MODUWMNL_CATEGORY_PATH map ON map.FULL_PATH = manual.CATEGORY
SET manual.CATEGORY_ID = map.CATEGORY_ID;

-- Confirm this returns 0 before continuing: SELECT COUNT(*) FROM MODUWMNL WHERE CATEGORY_ID IS NULL;
ALTER TABLE MODUWMNL MODIFY CATEGORY_ID BIGINT NOT NULL;
ALTER TABLE MODUWMNL ADD CONSTRAINT FK_EZHOWTOUSE_MNL_CATEGORY_V1
    FOREIGN KEY (CATEGORY_ID) REFERENCES MODUWMNL_CATEGORY (CATEGORY_ID);
ALTER TABLE MODUWMNL ADD KEY IX_MODUWMNL_01_NEW (USE_YN, LST_YN, CATEGORY_ID);
ALTER TABLE MODUWMNL DROP COLUMN CATEGORY;

DROP TABLE TMP_MODUWMNL_CATEGORY_PATH;
-- Keep MODUWMNL_CATEGORY_LEGACY as a rollback reference until the deployment is verified.
